/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VerificationStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'unverified' : IDL.Null,
  'rejected' : IDL.Text,
});
export const RevenueTrend = IDL.Variant({
  'up' : IDL.Null,
  'down' : IDL.Null,
  'flat' : IDL.Null,
});
export const CredentialSource = IDL.Variant({
  'stripe' : IDL.Null,
  'googleAnalytics' : IDL.Null,
  'paypal' : IDL.Null,
  'googleAdSense' : IDL.Null,
});
export const SourceBreakdown = IDL.Record({
  'source' : CredentialSource,
  'trafficVolume' : IDL.Nat,
  'monthlyRevenue' : IDL.Float64,
});
export const VerifiedMetrics = IDL.Record({
  'fetchedAt' : IDL.Int,
  'trafficVolume' : IDL.Nat,
  'revenueTrend' : RevenueTrend,
  'monthlyRevenue' : IDL.Float64,
  'sourceBreakdowns' : IDL.Vec(SourceBreakdown),
});
export const VerificationRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : VerificationStatus,
  'listingId' : IDL.Nat,
  'verifiedMetrics' : IDL.Opt(VerifiedMetrics),
  'submittedAt' : IDL.Int,
  'reviewedAt' : IDL.Opt(IDL.Int),
  'adminNote' : IDL.Opt(IDL.Text),
  'sellerId' : IDL.Text,
  'claimedTrafficVolume' : IDL.Nat,
  'claimedMonthlyRevenue' : IDL.Float64,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
});
export const ValuationInput = IDL.Record({
  'domainAuthority' : IDL.Nat,
  'revenueType' : IDL.Variant({
    'ads' : IDL.Null,
    'recurring' : IDL.Null,
    'affiliate' : IDL.Null,
    'product' : IDL.Null,
  }),
  'monthlyTraffic' : IDL.Nat,
  'trafficDiversification' : IDL.Variant({
    'mixed' : IDL.Null,
    'diverse' : IDL.Null,
    'single' : IDL.Null,
  }),
  'revenueTrend' : IDL.Variant({
    'up' : IDL.Null,
    'down' : IDL.Null,
    'flat' : IDL.Null,
  }),
  'domainAgeYears' : IDL.Nat,
  'monthlyRevenue' : IDL.Nat,
});
export const ValuationResult = IDL.Record({
  'baseMultiple' : IDL.Nat,
  'trendAdjustment' : IDL.Int,
  'daBonus' : IDL.Int,
  'estimatedMax' : IDL.Nat,
  'estimatedMin' : IDL.Nat,
  'seoScore' : IDL.Nat,
  'growthPotential' : IDL.Nat,
  'trafficBonus' : IDL.Int,
  'riskScore' : IDL.Nat,
});
export const ListingFilter = IDL.Record({
  'platform' : IDL.Opt(IDL.Text),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'niche' : IDL.Opt(IDL.Text),
});
export const ListingStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'sold' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'status' : ListingStatus,
  'title' : IDL.Text,
  'askingPrice' : IDL.Nat,
  'monthlyTraffic' : IDL.Nat,
  'listedDate' : Timestamp,
  'description' : IDL.Text,
  'platform' : IDL.Text,
  'sellerName' : IDL.Text,
  'niche' : IDL.Text,
  'monthlyRevenue' : IDL.Nat,
});
export const PerformanceReportInput = IDL.Record({ 'listingId' : IDL.Text });
export const PerformanceReport = IDL.Record({
  'spamScore' : IDL.Nat,
  'listingId' : IDL.Text,
  'overallGrade' : IDL.Text,
  'mobileScore' : IDL.Nat,
  'seoScore' : IDL.Nat,
  'reportedAt' : IDL.Int,
  'securityScore' : IDL.Nat,
  'speedScore' : IDL.Nat,
});
export const MockupSection = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
});
export const WebsiteBuilderMockup = IDL.Record({
  'primaryColor' : IDL.Text,
  'headline' : IDL.Text,
  'accentColor' : IDL.Text,
  'ctaText' : IDL.Text,
  'ctaSubtext' : IDL.Text,
  'secondaryColor' : IDL.Text,
  'sections' : IDL.Vec(MockupSection),
  'subheadline' : IDL.Text,
});
export const BidEntry = IDL.Record({
  'won' : IDL.Bool,
  'auctionEnded' : IDL.Bool,
  'listingId' : IDL.Nat,
  'bidAmount' : IDL.Nat,
  'placedAt' : Timestamp,
  'listingTitle' : IDL.Text,
  'isHighestBidder' : IDL.Bool,
});
export const CustomOrder = IDL.Record({
  'id' : IDL.Nat,
  'websiteType' : IDL.Text,
  'status' : IDL.Text,
  'sellerNotes' : IDL.Opt(IDL.Text),
  'contactName' : IDL.Text,
  'submittedAt' : Timestamp,
  'submittedBy' : IDL.Principal,
  'description' : IDL.Text,
  'contactEmail' : IDL.Text,
  'requirements' : IDL.Text,
  'budget' : IDL.Text,
  'timeline' : IDL.Text,
});
export const NotificationType = IDL.Variant({
  'outbid' : IDL.Record({ 'newHighestBid' : IDL.Nat, 'listingId' : IDL.Nat }),
  'purchaseConfirmed' : IDL.Record({
    'listingId' : IDL.Nat,
    'amount' : IDL.Nat,
  }),
  'auctionWon' : IDL.Record({ 'finalPrice' : IDL.Nat, 'listingId' : IDL.Nat }),
  'priceDrop' : IDL.Record({
    'listingId' : IDL.Nat,
    'oldPrice' : IDL.Nat,
    'newPrice' : IDL.Nat,
  }),
  'transferUpdate' : IDL.Record({
    'listingId' : IDL.Nat,
    'message' : IDL.Text,
  }),
});
export const BuyerNotificationView = IDL.Record({
  'id' : IDL.Nat,
  'notifType' : NotificationType,
  'createdAt' : Timestamp,
  'read' : IDL.Bool,
});
export const PurchaseRecord = IDL.Record({
  'id' : IDL.Nat,
  'completedAt' : Timestamp,
  'listingId' : IDL.Nat,
  'transferStatus' : IDL.Text,
  'seller' : IDL.Text,
  'listingTitle' : IDL.Text,
  'buyer' : IDL.Principal,
  'pricePaid' : IDL.Nat,
});
export const SearchQuery = IDL.Record({
  'naturalLanguage' : IDL.Opt(IDL.Text),
  'cmsType' : IDL.Opt(IDL.Text),
  'sortBy' : IDL.Variant({
    'newest' : IDL.Null,
    'priceDesc' : IDL.Null,
    'priceAsc' : IDL.Null,
    'bestMatch' : IDL.Null,
    'highestRating' : IDL.Null,
  }),
  'minTraffic' : IDL.Opt(IDL.Nat),
  'countryTraffic' : IDL.Opt(IDL.Text),
  'maxRevenue' : IDL.Opt(IDL.Nat),
  'minAgeYears' : IDL.Opt(IDL.Nat),
  'niche' : IDL.Opt(IDL.Text),
  'monetizationType' : IDL.Opt(IDL.Text),
  'minSeoScore' : IDL.Opt(IDL.Nat),
  'minRevenue' : IDL.Opt(IDL.Nat),
  'maxTraffic' : IDL.Opt(IDL.Nat),
});
export const SellerReview = IDL.Record({
  'id' : IDL.Text,
  'listingId' : IDL.Text,
  'reviewerName' : IDL.Text,
  'comment' : IDL.Text,
  'timestamp' : Timestamp,
  'rating' : IDL.Nat,
});
export const TrustScore = IDL.Record({
  'completionRate' : IDL.Nat,
  'hasRedFlags' : IDL.Bool,
  'tier' : IDL.Variant({
    'new' : IDL.Null,
    'trusted' : IDL.Null,
    'established' : IDL.Null,
    'caution' : IDL.Null,
  }),
  'score' : IDL.Nat,
  'isVerified' : IDL.Bool,
  'accountAgeDays' : IDL.Nat,
  'responseTimeHours' : IDL.Nat,
  'avgRating' : IDL.Nat,
  'transactionCount' : IDL.Nat,
});
export const VerifiedBadge = IDL.Record({
  'trend' : RevenueTrend,
  'listingId' : IDL.Nat,
  'trafficVolume' : IDL.Nat,
  'monthlyRevenue' : IDL.Float64,
  'sourceBreakdowns' : IDL.Vec(SourceBreakdown),
});
export const WishlistEntry = IDL.Record({
  'snapshotNiche' : IDL.Text,
  'listingId' : IDL.Nat,
  'snapshotPrice' : IDL.Nat,
  'snapshotTitle' : IDL.Text,
  'savedAt' : Timestamp,
  'snapshotUrl' : IDL.Text,
});
export const ContactMessageInput = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const CustomOrderInput = IDL.Record({
  'websiteType' : IDL.Text,
  'contactName' : IDL.Text,
  'description' : IDL.Text,
  'contactEmail' : IDL.Text,
  'requirements' : IDL.Text,
  'budget' : IDL.Text,
  'timeline' : IDL.Text,
});
export const SellerReviewInput = IDL.Record({
  'listingId' : IDL.Text,
  'reviewerName' : IDL.Text,
  'comment' : IDL.Text,
  'sellerId' : IDL.Text,
  'rating' : IDL.Nat,
});
export const CredentialToken = IDL.Record({
  'token' : IDL.Text,
  'refreshToken' : IDL.Opt(IDL.Text),
  'source' : CredentialSource,
});
export const SellerSubmissionInput = IDL.Record({
  'url' : IDL.Text,
  'askingPrice' : IDL.Nat,
  'monthlyTraffic' : IDL.Nat,
  'description' : IDL.Text,
  'platform' : IDL.Text,
  'niche' : IDL.Text,
  'contactEmail' : IDL.Text,
  'monthlyRevenue' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addToWishlist' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'adminApproveVerification' : IDL.Func([IDL.Nat], [], []),
  'adminListPendingVerifications' : IDL.Func(
      [],
      [IDL.Vec(VerificationRequest)],
      [],
    ),
  'adminRejectVerification' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'askAI' : IDL.Func([IDL.Text, IDL.Vec(ChatMessage)], [IDL.Text], []),
  'calculateValuation' : IDL.Func(
      [ValuationInput],
      [ValuationResult],
      ['query'],
    ),
  'checkWishlist' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'filterListings' : IDL.Func([ListingFilter], [IDL.Vec(Listing)], ['query']),
  'generatePerformanceReport' : IDL.Func(
      [PerformanceReportInput],
      [PerformanceReport],
      [],
    ),
  'generateWebsiteBuilderMockup' : IDL.Func(
      [IDL.Text, IDL.Text],
      [WebsiteBuilderMockup],
      [],
    ),
  'getBuyerBids' : IDL.Func([], [IDL.Vec(BidEntry)], ['query']),
  'getBuyerCustomOrders' : IDL.Func([], [IDL.Vec(CustomOrder)], ['query']),
  'getBuyerNotifications' : IDL.Func(
      [],
      [IDL.Vec(BuyerNotificationView)],
      ['query'],
    ),
  'getBuyerPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
  'getCustomOrders' : IDL.Func([], [IDL.Vec(CustomOrder)], ['query']),
  'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
  'getListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getRecommendations' : IDL.Func([SearchQuery], [IDL.Vec(Listing)], ['query']),
  'getReviews' : IDL.Func([IDL.Text], [IDL.Vec(SellerReview)], ['query']),
  'getSellerListings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getSellerTrustScore' : IDL.Func([IDL.Text], [TrustScore], ['query']),
  'getVerificationStatus' : IDL.Func(
      [IDL.Nat],
      [VerificationStatus],
      ['query'],
    ),
  'getVerifiedBadge' : IDL.Func([IDL.Nat], [IDL.Opt(VerifiedBadge)], ['query']),
  'getWishlist' : IDL.Func([], [IDL.Vec(WishlistEntry)], ['query']),
  'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'refreshVerificationMetrics' : IDL.Func([IDL.Nat], [], []),
  'removeFromWishlist' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'smartSearch' : IDL.Func([SearchQuery], [IDL.Vec(Listing)], ['query']),
  'submitContact' : IDL.Func([ContactMessageInput], [], []),
  'submitCustomOrder' : IDL.Func([CustomOrderInput], [IDL.Nat], []),
  'submitReview' : IDL.Func(
      [SellerReviewInput],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'submitVerificationRequest' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Nat, IDL.Vec(CredentialToken)],
      [IDL.Nat],
      [],
    ),
  'submitWebsite' : IDL.Func([SellerSubmissionInput], [], []),
  'updateCustomOrderStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'websiteTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'unverified' : IDL.Null,
    'rejected' : IDL.Text,
  });
  const RevenueTrend = IDL.Variant({
    'up' : IDL.Null,
    'down' : IDL.Null,
    'flat' : IDL.Null,
  });
  const CredentialSource = IDL.Variant({
    'stripe' : IDL.Null,
    'googleAnalytics' : IDL.Null,
    'paypal' : IDL.Null,
    'googleAdSense' : IDL.Null,
  });
  const SourceBreakdown = IDL.Record({
    'source' : CredentialSource,
    'trafficVolume' : IDL.Nat,
    'monthlyRevenue' : IDL.Float64,
  });
  const VerifiedMetrics = IDL.Record({
    'fetchedAt' : IDL.Int,
    'trafficVolume' : IDL.Nat,
    'revenueTrend' : RevenueTrend,
    'monthlyRevenue' : IDL.Float64,
    'sourceBreakdowns' : IDL.Vec(SourceBreakdown),
  });
  const VerificationRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : VerificationStatus,
    'listingId' : IDL.Nat,
    'verifiedMetrics' : IDL.Opt(VerifiedMetrics),
    'submittedAt' : IDL.Int,
    'reviewedAt' : IDL.Opt(IDL.Int),
    'adminNote' : IDL.Opt(IDL.Text),
    'sellerId' : IDL.Text,
    'claimedTrafficVolume' : IDL.Nat,
    'claimedMonthlyRevenue' : IDL.Float64,
  });
  const ChatMessage = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
  const ValuationInput = IDL.Record({
    'domainAuthority' : IDL.Nat,
    'revenueType' : IDL.Variant({
      'ads' : IDL.Null,
      'recurring' : IDL.Null,
      'affiliate' : IDL.Null,
      'product' : IDL.Null,
    }),
    'monthlyTraffic' : IDL.Nat,
    'trafficDiversification' : IDL.Variant({
      'mixed' : IDL.Null,
      'diverse' : IDL.Null,
      'single' : IDL.Null,
    }),
    'revenueTrend' : IDL.Variant({
      'up' : IDL.Null,
      'down' : IDL.Null,
      'flat' : IDL.Null,
    }),
    'domainAgeYears' : IDL.Nat,
    'monthlyRevenue' : IDL.Nat,
  });
  const ValuationResult = IDL.Record({
    'baseMultiple' : IDL.Nat,
    'trendAdjustment' : IDL.Int,
    'daBonus' : IDL.Int,
    'estimatedMax' : IDL.Nat,
    'estimatedMin' : IDL.Nat,
    'seoScore' : IDL.Nat,
    'growthPotential' : IDL.Nat,
    'trafficBonus' : IDL.Int,
    'riskScore' : IDL.Nat,
  });
  const ListingFilter = IDL.Record({
    'platform' : IDL.Opt(IDL.Text),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'niche' : IDL.Opt(IDL.Text),
  });
  const ListingStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'sold' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'status' : ListingStatus,
    'title' : IDL.Text,
    'askingPrice' : IDL.Nat,
    'monthlyTraffic' : IDL.Nat,
    'listedDate' : Timestamp,
    'description' : IDL.Text,
    'platform' : IDL.Text,
    'sellerName' : IDL.Text,
    'niche' : IDL.Text,
    'monthlyRevenue' : IDL.Nat,
  });
  const PerformanceReportInput = IDL.Record({ 'listingId' : IDL.Text });
  const PerformanceReport = IDL.Record({
    'spamScore' : IDL.Nat,
    'listingId' : IDL.Text,
    'overallGrade' : IDL.Text,
    'mobileScore' : IDL.Nat,
    'seoScore' : IDL.Nat,
    'reportedAt' : IDL.Int,
    'securityScore' : IDL.Nat,
    'speedScore' : IDL.Nat,
  });
  const MockupSection = IDL.Record({ 'title' : IDL.Text, 'body' : IDL.Text });
  const WebsiteBuilderMockup = IDL.Record({
    'primaryColor' : IDL.Text,
    'headline' : IDL.Text,
    'accentColor' : IDL.Text,
    'ctaText' : IDL.Text,
    'ctaSubtext' : IDL.Text,
    'secondaryColor' : IDL.Text,
    'sections' : IDL.Vec(MockupSection),
    'subheadline' : IDL.Text,
  });
  const BidEntry = IDL.Record({
    'won' : IDL.Bool,
    'auctionEnded' : IDL.Bool,
    'listingId' : IDL.Nat,
    'bidAmount' : IDL.Nat,
    'placedAt' : Timestamp,
    'listingTitle' : IDL.Text,
    'isHighestBidder' : IDL.Bool,
  });
  const CustomOrder = IDL.Record({
    'id' : IDL.Nat,
    'websiteType' : IDL.Text,
    'status' : IDL.Text,
    'sellerNotes' : IDL.Opt(IDL.Text),
    'contactName' : IDL.Text,
    'submittedAt' : Timestamp,
    'submittedBy' : IDL.Principal,
    'description' : IDL.Text,
    'contactEmail' : IDL.Text,
    'requirements' : IDL.Text,
    'budget' : IDL.Text,
    'timeline' : IDL.Text,
  });
  const NotificationType = IDL.Variant({
    'outbid' : IDL.Record({ 'newHighestBid' : IDL.Nat, 'listingId' : IDL.Nat }),
    'purchaseConfirmed' : IDL.Record({
      'listingId' : IDL.Nat,
      'amount' : IDL.Nat,
    }),
    'auctionWon' : IDL.Record({
      'finalPrice' : IDL.Nat,
      'listingId' : IDL.Nat,
    }),
    'priceDrop' : IDL.Record({
      'listingId' : IDL.Nat,
      'oldPrice' : IDL.Nat,
      'newPrice' : IDL.Nat,
    }),
    'transferUpdate' : IDL.Record({
      'listingId' : IDL.Nat,
      'message' : IDL.Text,
    }),
  });
  const BuyerNotificationView = IDL.Record({
    'id' : IDL.Nat,
    'notifType' : NotificationType,
    'createdAt' : Timestamp,
    'read' : IDL.Bool,
  });
  const PurchaseRecord = IDL.Record({
    'id' : IDL.Nat,
    'completedAt' : Timestamp,
    'listingId' : IDL.Nat,
    'transferStatus' : IDL.Text,
    'seller' : IDL.Text,
    'listingTitle' : IDL.Text,
    'buyer' : IDL.Principal,
    'pricePaid' : IDL.Nat,
  });
  const SearchQuery = IDL.Record({
    'naturalLanguage' : IDL.Opt(IDL.Text),
    'cmsType' : IDL.Opt(IDL.Text),
    'sortBy' : IDL.Variant({
      'newest' : IDL.Null,
      'priceDesc' : IDL.Null,
      'priceAsc' : IDL.Null,
      'bestMatch' : IDL.Null,
      'highestRating' : IDL.Null,
    }),
    'minTraffic' : IDL.Opt(IDL.Nat),
    'countryTraffic' : IDL.Opt(IDL.Text),
    'maxRevenue' : IDL.Opt(IDL.Nat),
    'minAgeYears' : IDL.Opt(IDL.Nat),
    'niche' : IDL.Opt(IDL.Text),
    'monetizationType' : IDL.Opt(IDL.Text),
    'minSeoScore' : IDL.Opt(IDL.Nat),
    'minRevenue' : IDL.Opt(IDL.Nat),
    'maxTraffic' : IDL.Opt(IDL.Nat),
  });
  const SellerReview = IDL.Record({
    'id' : IDL.Text,
    'listingId' : IDL.Text,
    'reviewerName' : IDL.Text,
    'comment' : IDL.Text,
    'timestamp' : Timestamp,
    'rating' : IDL.Nat,
  });
  const TrustScore = IDL.Record({
    'completionRate' : IDL.Nat,
    'hasRedFlags' : IDL.Bool,
    'tier' : IDL.Variant({
      'new' : IDL.Null,
      'trusted' : IDL.Null,
      'established' : IDL.Null,
      'caution' : IDL.Null,
    }),
    'score' : IDL.Nat,
    'isVerified' : IDL.Bool,
    'accountAgeDays' : IDL.Nat,
    'responseTimeHours' : IDL.Nat,
    'avgRating' : IDL.Nat,
    'transactionCount' : IDL.Nat,
  });
  const VerifiedBadge = IDL.Record({
    'trend' : RevenueTrend,
    'listingId' : IDL.Nat,
    'trafficVolume' : IDL.Nat,
    'monthlyRevenue' : IDL.Float64,
    'sourceBreakdowns' : IDL.Vec(SourceBreakdown),
  });
  const WishlistEntry = IDL.Record({
    'snapshotNiche' : IDL.Text,
    'listingId' : IDL.Nat,
    'snapshotPrice' : IDL.Nat,
    'snapshotTitle' : IDL.Text,
    'savedAt' : Timestamp,
    'snapshotUrl' : IDL.Text,
  });
  const ContactMessageInput = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const CustomOrderInput = IDL.Record({
    'websiteType' : IDL.Text,
    'contactName' : IDL.Text,
    'description' : IDL.Text,
    'contactEmail' : IDL.Text,
    'requirements' : IDL.Text,
    'budget' : IDL.Text,
    'timeline' : IDL.Text,
  });
  const SellerReviewInput = IDL.Record({
    'listingId' : IDL.Text,
    'reviewerName' : IDL.Text,
    'comment' : IDL.Text,
    'sellerId' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const CredentialToken = IDL.Record({
    'token' : IDL.Text,
    'refreshToken' : IDL.Opt(IDL.Text),
    'source' : CredentialSource,
  });
  const SellerSubmissionInput = IDL.Record({
    'url' : IDL.Text,
    'askingPrice' : IDL.Nat,
    'monthlyTraffic' : IDL.Nat,
    'description' : IDL.Text,
    'platform' : IDL.Text,
    'niche' : IDL.Text,
    'contactEmail' : IDL.Text,
    'monthlyRevenue' : IDL.Nat,
  });
  
  return IDL.Service({
    'addToWishlist' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'adminApproveVerification' : IDL.Func([IDL.Nat], [], []),
    'adminListPendingVerifications' : IDL.Func(
        [],
        [IDL.Vec(VerificationRequest)],
        [],
      ),
    'adminRejectVerification' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'askAI' : IDL.Func([IDL.Text, IDL.Vec(ChatMessage)], [IDL.Text], []),
    'calculateValuation' : IDL.Func(
        [ValuationInput],
        [ValuationResult],
        ['query'],
      ),
    'checkWishlist' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'filterListings' : IDL.Func([ListingFilter], [IDL.Vec(Listing)], ['query']),
    'generatePerformanceReport' : IDL.Func(
        [PerformanceReportInput],
        [PerformanceReport],
        [],
      ),
    'generateWebsiteBuilderMockup' : IDL.Func(
        [IDL.Text, IDL.Text],
        [WebsiteBuilderMockup],
        [],
      ),
    'getBuyerBids' : IDL.Func([], [IDL.Vec(BidEntry)], ['query']),
    'getBuyerCustomOrders' : IDL.Func([], [IDL.Vec(CustomOrder)], ['query']),
    'getBuyerNotifications' : IDL.Func(
        [],
        [IDL.Vec(BuyerNotificationView)],
        ['query'],
      ),
    'getBuyerPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
    'getCustomOrders' : IDL.Func([], [IDL.Vec(CustomOrder)], ['query']),
    'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
    'getListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getRecommendations' : IDL.Func(
        [SearchQuery],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getReviews' : IDL.Func([IDL.Text], [IDL.Vec(SellerReview)], ['query']),
    'getSellerListings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getSellerTrustScore' : IDL.Func([IDL.Text], [TrustScore], ['query']),
    'getVerificationStatus' : IDL.Func(
        [IDL.Nat],
        [VerificationStatus],
        ['query'],
      ),
    'getVerifiedBadge' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(VerifiedBadge)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(WishlistEntry)], ['query']),
    'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'refreshVerificationMetrics' : IDL.Func([IDL.Nat], [], []),
    'removeFromWishlist' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'smartSearch' : IDL.Func([SearchQuery], [IDL.Vec(Listing)], ['query']),
    'submitContact' : IDL.Func([ContactMessageInput], [], []),
    'submitCustomOrder' : IDL.Func([CustomOrderInput], [IDL.Nat], []),
    'submitReview' : IDL.Func(
        [SellerReviewInput],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'submitVerificationRequest' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Nat, IDL.Vec(CredentialToken)],
        [IDL.Nat],
        [],
      ),
    'submitWebsite' : IDL.Func([SellerSubmissionInput], [], []),
    'updateCustomOrderStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'websiteTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };