/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BidEntry {
  'won' : boolean,
  'auctionEnded' : boolean,
  'listingId' : bigint,
  'bidAmount' : bigint,
  'placedAt' : Timestamp,
  'listingTitle' : string,
  'isHighestBidder' : boolean,
}
export interface BuyerNotificationView {
  'id' : bigint,
  'notifType' : NotificationType,
  'createdAt' : Timestamp,
  'read' : boolean,
}
export interface ChatMessage { 'content' : string, 'role' : string }
export interface ContactMessageInput {
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
}
export type CredentialSource = { 'stripe' : null } |
  { 'googleAnalytics' : null } |
  { 'paypal' : null } |
  { 'googleAdSense' : null };
export interface CredentialToken {
  'token' : string,
  'refreshToken' : [] | [string],
  'source' : CredentialSource,
}
export interface CustomOrder {
  'id' : bigint,
  'websiteType' : string,
  'status' : string,
  'sellerNotes' : [] | [string],
  'contactName' : string,
  'submittedAt' : Timestamp,
  'submittedBy' : Principal,
  'description' : string,
  'contactEmail' : string,
  'requirements' : string,
  'budget' : string,
  'timeline' : string,
}
export interface CustomOrderInput {
  'websiteType' : string,
  'contactName' : string,
  'description' : string,
  'contactEmail' : string,
  'requirements' : string,
  'budget' : string,
  'timeline' : string,
}
export interface Listing {
  'id' : bigint,
  'url' : string,
  'status' : ListingStatus,
  'title' : string,
  'askingPrice' : bigint,
  'monthlyTraffic' : bigint,
  'listedDate' : Timestamp,
  'description' : string,
  'platform' : string,
  'sellerName' : string,
  'niche' : string,
  'monthlyRevenue' : bigint,
}
export interface ListingFilter {
  'platform' : [] | [string],
  'maxPrice' : [] | [bigint],
  'niche' : [] | [string],
}
export type ListingStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'sold' : null };
export interface MockupSection { 'title' : string, 'body' : string }
export type NotificationType = {
    'outbid' : { 'newHighestBid' : bigint, 'listingId' : bigint }
  } |
  { 'purchaseConfirmed' : { 'listingId' : bigint, 'amount' : bigint } } |
  { 'auctionWon' : { 'finalPrice' : bigint, 'listingId' : bigint } } |
  {
    'priceDrop' : {
      'listingId' : bigint,
      'oldPrice' : bigint,
      'newPrice' : bigint,
    }
  } |
  { 'transferUpdate' : { 'listingId' : bigint, 'message' : string } };
export interface PerformanceReport {
  'spamScore' : bigint,
  'listingId' : string,
  'overallGrade' : string,
  'mobileScore' : bigint,
  'seoScore' : bigint,
  'reportedAt' : bigint,
  'securityScore' : bigint,
  'speedScore' : bigint,
}
export interface PerformanceReportInput { 'listingId' : string }
export interface PurchaseRecord {
  'id' : bigint,
  'completedAt' : Timestamp,
  'listingId' : bigint,
  'transferStatus' : string,
  'seller' : string,
  'listingTitle' : string,
  'buyer' : Principal,
  'pricePaid' : bigint,
}
export type RevenueTrend = { 'up' : null } |
  { 'down' : null } |
  { 'flat' : null };
export interface SearchQuery {
  'naturalLanguage' : [] | [string],
  'cmsType' : [] | [string],
  'sortBy' : { 'newest' : null } |
    { 'priceDesc' : null } |
    { 'priceAsc' : null } |
    { 'bestMatch' : null } |
    { 'highestRating' : null },
  'minTraffic' : [] | [bigint],
  'countryTraffic' : [] | [string],
  'maxRevenue' : [] | [bigint],
  'minAgeYears' : [] | [bigint],
  'niche' : [] | [string],
  'monetizationType' : [] | [string],
  'minSeoScore' : [] | [bigint],
  'minRevenue' : [] | [bigint],
  'maxTraffic' : [] | [bigint],
}
export interface SellerReview {
  'id' : string,
  'listingId' : string,
  'reviewerName' : string,
  'comment' : string,
  'timestamp' : Timestamp,
  'rating' : bigint,
}
export interface SellerReviewInput {
  'listingId' : string,
  'reviewerName' : string,
  'comment' : string,
  'sellerId' : string,
  'rating' : bigint,
}
export interface SellerSubmissionInput {
  'url' : string,
  'askingPrice' : bigint,
  'monthlyTraffic' : bigint,
  'description' : string,
  'platform' : string,
  'niche' : string,
  'contactEmail' : string,
  'monthlyRevenue' : bigint,
}
export interface SourceBreakdown {
  'source' : CredentialSource,
  'trafficVolume' : bigint,
  'monthlyRevenue' : number,
}
export type Timestamp = bigint;
export interface TrustScore {
  'completionRate' : bigint,
  'hasRedFlags' : boolean,
  'tier' : { 'new' : null } |
    { 'trusted' : null } |
    { 'established' : null } |
    { 'caution' : null },
  'score' : bigint,
  'isVerified' : boolean,
  'accountAgeDays' : bigint,
  'responseTimeHours' : bigint,
  'avgRating' : bigint,
  'transactionCount' : bigint,
}
export interface ValuationInput {
  'domainAuthority' : bigint,
  'revenueType' : { 'ads' : null } |
    { 'recurring' : null } |
    { 'affiliate' : null } |
    { 'product' : null },
  'monthlyTraffic' : bigint,
  'trafficDiversification' : { 'mixed' : null } |
    { 'diverse' : null } |
    { 'single' : null },
  'revenueTrend' : { 'up' : null } |
    { 'down' : null } |
    { 'flat' : null },
  'domainAgeYears' : bigint,
  'monthlyRevenue' : bigint,
}
export interface ValuationResult {
  'baseMultiple' : bigint,
  'trendAdjustment' : bigint,
  'daBonus' : bigint,
  'estimatedMax' : bigint,
  'estimatedMin' : bigint,
  'seoScore' : bigint,
  'growthPotential' : bigint,
  'trafficBonus' : bigint,
  'riskScore' : bigint,
}
export interface VerificationRequest {
  'id' : bigint,
  'status' : VerificationStatus,
  'listingId' : bigint,
  'verifiedMetrics' : [] | [VerifiedMetrics],
  'submittedAt' : bigint,
  'reviewedAt' : [] | [bigint],
  'adminNote' : [] | [string],
  'sellerId' : string,
  'claimedTrafficVolume' : bigint,
  'claimedMonthlyRevenue' : number,
}
export type VerificationStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'unverified' : null } |
  { 'rejected' : string };
export interface VerifiedBadge {
  'trend' : RevenueTrend,
  'listingId' : bigint,
  'trafficVolume' : bigint,
  'monthlyRevenue' : number,
  'sourceBreakdowns' : Array<SourceBreakdown>,
}
export interface VerifiedMetrics {
  'fetchedAt' : bigint,
  'trafficVolume' : bigint,
  'revenueTrend' : RevenueTrend,
  'monthlyRevenue' : number,
  'sourceBreakdowns' : Array<SourceBreakdown>,
}
export interface WebsiteBuilderMockup {
  'primaryColor' : string,
  'headline' : string,
  'accentColor' : string,
  'ctaText' : string,
  'ctaSubtext' : string,
  'secondaryColor' : string,
  'sections' : Array<MockupSection>,
  'subheadline' : string,
}
export interface WishlistEntry {
  'snapshotNiche' : string,
  'listingId' : bigint,
  'snapshotPrice' : bigint,
  'snapshotTitle' : string,
  'savedAt' : Timestamp,
  'snapshotUrl' : string,
}
export interface _SERVICE {
  'addToWishlist' : ActorMethod<[bigint], boolean>,
  'adminApproveVerification' : ActorMethod<[bigint], undefined>,
  'adminListPendingVerifications' : ActorMethod<[], Array<VerificationRequest>>,
  'adminRejectVerification' : ActorMethod<[bigint, string], undefined>,
  'askAI' : ActorMethod<[string, Array<ChatMessage>], string>,
  'calculateValuation' : ActorMethod<[ValuationInput], ValuationResult>,
  'checkWishlist' : ActorMethod<[bigint], boolean>,
  'filterListings' : ActorMethod<[ListingFilter], Array<Listing>>,
  'generatePerformanceReport' : ActorMethod<
    [PerformanceReportInput],
    PerformanceReport
  >,
  'generateWebsiteBuilderMockup' : ActorMethod<
    [string, string],
    WebsiteBuilderMockup
  >,
  'getBuyerBids' : ActorMethod<[], Array<BidEntry>>,
  'getBuyerCustomOrders' : ActorMethod<[], Array<CustomOrder>>,
  'getBuyerNotifications' : ActorMethod<[], Array<BuyerNotificationView>>,
  'getBuyerPurchases' : ActorMethod<[], Array<PurchaseRecord>>,
  'getCustomOrders' : ActorMethod<[], Array<CustomOrder>>,
  'getListing' : ActorMethod<[bigint], [] | [Listing]>,
  'getListings' : ActorMethod<[], Array<Listing>>,
  'getRecommendations' : ActorMethod<[SearchQuery], Array<Listing>>,
  'getReviews' : ActorMethod<[string], Array<SellerReview>>,
  'getSellerListings' : ActorMethod<[Principal], Array<Listing>>,
  'getSellerTrustScore' : ActorMethod<[string], TrustScore>,
  'getVerificationStatus' : ActorMethod<[bigint], VerificationStatus>,
  'getVerifiedBadge' : ActorMethod<[bigint], [] | [VerifiedBadge]>,
  'getWishlist' : ActorMethod<[], Array<WishlistEntry>>,
  'markNotificationRead' : ActorMethod<[bigint], boolean>,
  'refreshVerificationMetrics' : ActorMethod<[bigint], undefined>,
  'removeFromWishlist' : ActorMethod<[bigint], boolean>,
  'smartSearch' : ActorMethod<[SearchQuery], Array<Listing>>,
  'submitContact' : ActorMethod<[ContactMessageInput], undefined>,
  'submitCustomOrder' : ActorMethod<[CustomOrderInput], bigint>,
  'submitReview' : ActorMethod<
    [SellerReviewInput],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'submitVerificationRequest' : ActorMethod<
    [bigint, number, bigint, Array<CredentialToken>],
    bigint
  >,
  'submitWebsite' : ActorMethod<[SellerSubmissionInput], undefined>,
  'updateCustomOrderStatus' : ActorMethod<
    [string, string, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'websiteTypes' : ActorMethod<[], Array<string>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];