/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SourceBreakdown {
    source: CredentialSource;
    trafficVolume: bigint;
    monthlyRevenue: number;
}
export type Timestamp = bigint;
export interface SellerReviewInput {
    listingId: string;
    reviewerName: string;
    comment: string;
    sellerId: string;
    rating: bigint;
}
export interface CustomOrderInput {
    websiteType: string;
    contactName: string;
    description: string;
    contactEmail: string;
    requirements: string;
    budget: string;
    timeline: string;
}
export interface PerformanceReport {
    spamScore: bigint;
    listingId: string;
    overallGrade: string;
    mobileScore: bigint;
    seoScore: bigint;
    reportedAt: bigint;
    securityScore: bigint;
    speedScore: bigint;
}
export interface VerifiedMetrics {
    fetchedAt: bigint;
    trafficVolume: bigint;
    revenueTrend: RevenueTrend;
    monthlyRevenue: number;
    sourceBreakdowns: Array<SourceBreakdown>;
}
export interface SellerReview {
    id: string;
    listingId: string;
    reviewerName: string;
    comment: string;
    timestamp: Timestamp;
    rating: bigint;
}
export interface ContactMessageInput {
    subject: string;
    name: string;
    email: string;
    message: string;
}
export interface ChatMessage {
    content: string;
    role: string;
}
export interface CustomOrder {
    id: bigint;
    websiteType: string;
    status: string;
    sellerNotes?: string;
    contactName: string;
    submittedAt: Timestamp;
    submittedBy: Principal;
    description: string;
    contactEmail: string;
    requirements: string;
    budget: string;
    timeline: string;
}
export interface CredentialToken {
    token: string;
    refreshToken?: string;
    source: CredentialSource;
}
export interface WebsiteBuilderMockup {
    primaryColor: string;
    headline: string;
    accentColor: string;
    ctaText: string;
    ctaSubtext: string;
    secondaryColor: string;
    sections: Array<MockupSection>;
    subheadline: string;
}
export interface VerifiedBadge {
    trend: RevenueTrend;
    listingId: bigint;
    trafficVolume: bigint;
    monthlyRevenue: number;
    sourceBreakdowns: Array<SourceBreakdown>;
}
export interface Listing {
    id: bigint;
    url: string;
    status: ListingStatus;
    title: string;
    askingPrice: bigint;
    monthlyTraffic: bigint;
    listedDate: Timestamp;
    description: string;
    platform: string;
    sellerName: string;
    niche: string;
    monthlyRevenue: bigint;
}
export interface TrustScore {
    completionRate: bigint;
    hasRedFlags: boolean;
    tier: Variant_new_trusted_established_caution;
    score: bigint;
    isVerified: boolean;
    accountAgeDays: bigint;
    responseTimeHours: bigint;
    avgRating: bigint;
    transactionCount: bigint;
}
export interface SearchQuery {
    naturalLanguage?: string;
    cmsType?: string;
    sortBy: Variant_newest_priceDesc_priceAsc_bestMatch_highestRating;
    minTraffic?: bigint;
    countryTraffic?: string;
    maxRevenue?: bigint;
    minAgeYears?: bigint;
    niche?: string;
    monetizationType?: string;
    minSeoScore?: bigint;
    minRevenue?: bigint;
    maxTraffic?: bigint;
}
export interface ValuationInput {
    domainAuthority: bigint;
    revenueType: Variant_ads_recurring_affiliate_product;
    monthlyTraffic: bigint;
    trafficDiversification: Variant_mixed_diverse_single;
    revenueTrend: RevenueTrend;
    domainAgeYears: bigint;
    monthlyRevenue: bigint;
}
export interface ValuationResult {
    baseMultiple: bigint;
    trendAdjustment: bigint;
    daBonus: bigint;
    estimatedMax: bigint;
    estimatedMin: bigint;
    seoScore: bigint;
    growthPotential: bigint;
    trafficBonus: bigint;
    riskScore: bigint;
}
export interface BidEntry {
    won: boolean;
    auctionEnded: boolean;
    listingId: bigint;
    bidAmount: bigint;
    placedAt: Timestamp;
    listingTitle: string;
    isHighestBidder: boolean;
}
export type VerificationStatus = {
    __kind__: "verified";
    verified: null;
} | {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "unverified";
    unverified: null;
} | {
    __kind__: "rejected";
    rejected: string;
};
export interface WishlistEntry {
    snapshotNiche: string;
    listingId: bigint;
    snapshotPrice: bigint;
    snapshotTitle: string;
    savedAt: Timestamp;
    snapshotUrl: string;
}
export type NotificationType = {
    __kind__: "outbid";
    outbid: {
        newHighestBid: bigint;
        listingId: bigint;
    };
} | {
    __kind__: "purchaseConfirmed";
    purchaseConfirmed: {
        listingId: bigint;
        amount: bigint;
    };
} | {
    __kind__: "auctionWon";
    auctionWon: {
        finalPrice: bigint;
        listingId: bigint;
    };
} | {
    __kind__: "priceDrop";
    priceDrop: {
        listingId: bigint;
        oldPrice: bigint;
        newPrice: bigint;
    };
} | {
    __kind__: "transferUpdate";
    transferUpdate: {
        listingId: bigint;
        message: string;
    };
};
export interface ListingFilter {
    platform?: string;
    maxPrice?: bigint;
    niche?: string;
}
export interface PurchaseRecord {
    id: bigint;
    completedAt: Timestamp;
    listingId: bigint;
    transferStatus: string;
    seller: string;
    listingTitle: string;
    buyer: Principal;
    pricePaid: bigint;
}
export interface BuyerNotificationView {
    id: bigint;
    notifType: NotificationType;
    createdAt: Timestamp;
    read: boolean;
}
export interface PerformanceReportInput {
    listingId: string;
}
export interface SellerSubmissionInput {
    url: string;
    askingPrice: bigint;
    monthlyTraffic: bigint;
    description: string;
    platform: string;
    niche: string;
    contactEmail: string;
    monthlyRevenue: bigint;
}
export interface MockupSection {
    title: string;
    body: string;
}
export interface VerificationRequest {
    id: bigint;
    status: VerificationStatus;
    listingId: bigint;
    verifiedMetrics?: VerifiedMetrics;
    submittedAt: bigint;
    reviewedAt?: bigint;
    adminNote?: string;
    sellerId: string;
    claimedTrafficVolume: bigint;
    claimedMonthlyRevenue: number;
}
export enum CredentialSource {
    stripe = "stripe",
    googleAnalytics = "googleAnalytics",
    paypal = "paypal",
    googleAdSense = "googleAdSense"
}
export enum ListingStatus {
    active = "active",
    pending = "pending",
    sold = "sold"
}
export enum RevenueTrend {
    up = "up",
    down = "down",
    flat = "flat"
}
export enum Variant_ads_recurring_affiliate_product {
    ads = "ads",
    recurring = "recurring",
    affiliate = "affiliate",
    product = "product"
}
export enum Variant_mixed_diverse_single {
    mixed = "mixed",
    diverse = "diverse",
    single = "single"
}
export enum Variant_new_trusted_established_caution {
    new_ = "new",
    trusted = "trusted",
    established = "established",
    caution = "caution"
}
export enum Variant_newest_priceDesc_priceAsc_bestMatch_highestRating {
    newest = "newest",
    priceDesc = "priceDesc",
    priceAsc = "priceAsc",
    bestMatch = "bestMatch",
    highestRating = "highestRating"
}
export interface backendInterface {
    addToWishlist(listingId: bigint): Promise<boolean>;
    adminApproveVerification(requestId: bigint): Promise<void>;
    adminListPendingVerifications(): Promise<Array<VerificationRequest>>;
    adminRejectVerification(requestId: bigint, reason: string): Promise<void>;
    askAI(message: string, conversationHistory: Array<ChatMessage>): Promise<string>;
    calculateValuation(input: ValuationInput): Promise<ValuationResult>;
    checkWishlist(listingId: bigint): Promise<boolean>;
    filterListings(filter: ListingFilter): Promise<Array<Listing>>;
    generatePerformanceReport(input: PerformanceReportInput): Promise<PerformanceReport>;
    generateWebsiteBuilderMockup(niche: string, description: string): Promise<WebsiteBuilderMockup>;
    getBuyerBids(): Promise<Array<BidEntry>>;
    getBuyerCustomOrders(): Promise<Array<CustomOrder>>;
    getBuyerNotifications(): Promise<Array<BuyerNotificationView>>;
    getBuyerPurchases(): Promise<Array<PurchaseRecord>>;
    getCustomOrders(): Promise<Array<CustomOrder>>;
    getListing(id: bigint): Promise<Listing | null>;
    getListings(): Promise<Array<Listing>>;
    getRecommendations(searchQuery: SearchQuery): Promise<Array<Listing>>;
    getReviews(listingId: string): Promise<Array<SellerReview>>;
    getSellerListings(sellerPrincipal: Principal): Promise<Array<Listing>>;
    getSellerTrustScore(sellerId: string): Promise<TrustScore>;
    getVerificationStatus(listingId: bigint): Promise<VerificationStatus>;
    getVerifiedBadge(listingId: bigint): Promise<VerifiedBadge | null>;
    getWishlist(): Promise<Array<WishlistEntry>>;
    markNotificationRead(notifId: bigint): Promise<boolean>;
    refreshVerificationMetrics(listingId: bigint): Promise<void>;
    removeFromWishlist(listingId: bigint): Promise<boolean>;
    smartSearch(searchQuery: SearchQuery): Promise<Array<Listing>>;
    submitContact(input: ContactMessageInput): Promise<void>;
    submitCustomOrder(input: CustomOrderInput): Promise<bigint>;
    submitReview(review: SellerReviewInput): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    submitVerificationRequest(listingId: bigint, claimedMonthlyRevenue: number, claimedTrafficVolume: bigint, credentialTokens: Array<CredentialToken>): Promise<bigint>;
    submitWebsite(input: SellerSubmissionInput): Promise<void>;
    updateCustomOrderStatus(orderId: string, status: string, notes: string | null): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    websiteTypes(): Promise<Array<string>>;
}
import type { BuyerNotificationView as _BuyerNotificationView, CredentialSource as _CredentialSource, CredentialToken as _CredentialToken, CustomOrder as _CustomOrder, Listing as _Listing, ListingFilter as _ListingFilter, ListingStatus as _ListingStatus, NotificationType as _NotificationType, RevenueTrend as _RevenueTrend, SearchQuery as _SearchQuery, SourceBreakdown as _SourceBreakdown, Timestamp as _Timestamp, TrustScore as _TrustScore, ValuationInput as _ValuationInput, VerificationRequest as _VerificationRequest, VerificationStatus as _VerificationStatus, VerifiedBadge as _VerifiedBadge, VerifiedMetrics as _VerifiedMetrics } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addToWishlist(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWishlist(arg0);
            return result;
        }
    }
    async adminApproveVerification(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveVerification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveVerification(arg0);
            return result;
        }
    }
    async adminListPendingVerifications(): Promise<Array<VerificationRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListPendingVerifications();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListPendingVerifications();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRejectVerification(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRejectVerification(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRejectVerification(arg0, arg1);
            return result;
        }
    }
    async askAI(arg0: string, arg1: Array<ChatMessage>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.askAI(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askAI(arg0, arg1);
            return result;
        }
    }
    async calculateValuation(arg0: ValuationInput): Promise<ValuationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateValuation(to_candid_ValuationInput_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateValuation(to_candid_ValuationInput_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async checkWishlist(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkWishlist(arg0);
            return result;
        }
    }
    async filterListings(arg0: ListingFilter): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterListings(to_candid_ListingFilter_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterListings(to_candid_ListingFilter_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async generatePerformanceReport(arg0: PerformanceReportInput): Promise<PerformanceReport> {
        if (this.processError) {
            try {
                const result = await this.actor.generatePerformanceReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generatePerformanceReport(arg0);
            return result;
        }
    }
    async generateWebsiteBuilderMockup(arg0: string, arg1: string): Promise<WebsiteBuilderMockup> {
        if (this.processError) {
            try {
                const result = await this.actor.generateWebsiteBuilderMockup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateWebsiteBuilderMockup(arg0, arg1);
            return result;
        }
    }
    async getBuyerBids(): Promise<Array<BidEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuyerBids();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuyerBids();
            return result;
        }
    }
    async getBuyerCustomOrders(): Promise<Array<CustomOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuyerCustomOrders();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuyerCustomOrders();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBuyerNotifications(): Promise<Array<BuyerNotificationView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuyerNotifications();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuyerNotifications();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBuyerPurchases(): Promise<Array<PurchaseRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuyerPurchases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuyerPurchases();
            return result;
        }
    }
    async getCustomOrders(): Promise<Array<CustomOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomOrders();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomOrders();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListing(arg0: bigint): Promise<Listing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListings();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListings();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecommendations(arg0: SearchQuery): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendations(to_candid_SearchQuery_n39(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendations(to_candid_SearchQuery_n39(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviews(arg0: string): Promise<Array<SellerReview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews(arg0);
            return result;
        }
    }
    async getSellerListings(arg0: Principal): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSellerListings(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSellerListings(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSellerTrustScore(arg0: string): Promise<TrustScore> {
        if (this.processError) {
            try {
                const result = await this.actor.getSellerTrustScore(arg0);
                return from_candid_TrustScore_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSellerTrustScore(arg0);
            return from_candid_TrustScore_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVerificationStatus(arg0: bigint): Promise<VerificationStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerificationStatus(arg0);
                return from_candid_VerificationStatus_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerificationStatus(arg0);
            return from_candid_VerificationStatus_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVerifiedBadge(arg0: bigint): Promise<VerifiedBadge | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerifiedBadge(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerifiedBadge(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWishlist(): Promise<Array<WishlistEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWishlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWishlist();
            return result;
        }
    }
    async markNotificationRead(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async refreshVerificationMetrics(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshVerificationMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshVerificationMetrics(arg0);
            return result;
        }
    }
    async removeFromWishlist(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWishlist(arg0);
            return result;
        }
    }
    async smartSearch(arg0: SearchQuery): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.smartSearch(to_candid_SearchQuery_n39(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.smartSearch(to_candid_SearchQuery_n39(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContact(arg0: ContactMessageInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0);
            return result;
        }
    }
    async submitCustomOrder(arg0: CustomOrderInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCustomOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCustomOrder(arg0);
            return result;
        }
    }
    async submitReview(arg0: SellerReviewInput): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0);
                return from_candid_variant_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0);
            return from_candid_variant_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitVerificationRequest(arg0: bigint, arg1: number, arg2: bigint, arg3: Array<CredentialToken>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitVerificationRequest(arg0, arg1, arg2, to_candid_vec_n49(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitVerificationRequest(arg0, arg1, arg2, to_candid_vec_n49(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async submitWebsite(arg0: SellerSubmissionInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWebsite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWebsite(arg0);
            return result;
        }
    }
    async updateCustomOrderStatus(arg0: string, arg1: string, arg2: string | null): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomOrderStatus(arg0, arg1, to_candid_opt_n54(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomOrderStatus(arg0, arg1, to_candid_opt_n54(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async websiteTypes(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.websiteTypes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.websiteTypes();
            return result;
        }
    }
}
function from_candid_BuyerNotificationView_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BuyerNotificationView): BuyerNotificationView {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_CredentialSource_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CredentialSource): CredentialSource {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_CustomOrder_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomOrder): CustomOrder {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_ListingStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingStatus): ListingStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Listing_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Listing {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_RevenueTrend_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RevenueTrend): RevenueTrend {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_SourceBreakdown_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SourceBreakdown): SourceBreakdown {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_TrustScore_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrustScore): TrustScore {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationRequest_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationRequest): VerificationRequest {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_VerificationStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerificationStatus): VerificationStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_VerifiedBadge_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerifiedBadge): VerifiedBadge {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_VerifiedMetrics_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerifiedMetrics): VerifiedMetrics {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Listing]): Listing | null {
    return value.length === 0 ? null : from_candid_Listing_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VerifiedBadge]): VerifiedBadge | null {
    return value.length === 0 ? null : from_candid_VerifiedBadge_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VerifiedMetrics]): VerifiedMetrics | null {
    return value.length === 0 ? null : from_candid_VerifiedMetrics_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    source: _CredentialSource;
    trafficVolume: bigint;
    monthlyRevenue: number;
}): {
    source: CredentialSource;
    trafficVolume: bigint;
    monthlyRevenue: number;
} {
    return {
        source: from_candid_CredentialSource_n14(_uploadFile, _downloadFile, value.source),
        trafficVolume: value.trafficVolume,
        monthlyRevenue: value.monthlyRevenue
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    status: _ListingStatus;
    title: string;
    askingPrice: bigint;
    monthlyTraffic: bigint;
    listedDate: _Timestamp;
    description: string;
    platform: string;
    sellerName: string;
    niche: string;
    monthlyRevenue: bigint;
}): {
    id: bigint;
    url: string;
    status: ListingStatus;
    title: string;
    askingPrice: bigint;
    monthlyTraffic: bigint;
    listedDate: Timestamp;
    description: string;
    platform: string;
    sellerName: string;
    niche: string;
    monthlyRevenue: bigint;
} {
    return {
        id: value.id,
        url: value.url,
        status: from_candid_ListingStatus_n28(_uploadFile, _downloadFile, value.status),
        title: value.title,
        askingPrice: value.askingPrice,
        monthlyTraffic: value.monthlyTraffic,
        listedDate: value.listedDate,
        description: value.description,
        platform: value.platform,
        sellerName: value.sellerName,
        niche: value.niche,
        monthlyRevenue: value.monthlyRevenue
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _VerificationStatus;
    listingId: bigint;
    verifiedMetrics: [] | [_VerifiedMetrics];
    submittedAt: bigint;
    reviewedAt: [] | [bigint];
    adminNote: [] | [string];
    sellerId: string;
    claimedTrafficVolume: bigint;
    claimedMonthlyRevenue: number;
}): {
    id: bigint;
    status: VerificationStatus;
    listingId: bigint;
    verifiedMetrics?: VerifiedMetrics;
    submittedAt: bigint;
    reviewedAt?: bigint;
    adminNote?: string;
    sellerId: string;
    claimedTrafficVolume: bigint;
    claimedMonthlyRevenue: number;
} {
    return {
        id: value.id,
        status: from_candid_VerificationStatus_n4(_uploadFile, _downloadFile, value.status),
        listingId: value.listingId,
        verifiedMetrics: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.verifiedMetrics)),
        submittedAt: value.submittedAt,
        reviewedAt: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.reviewedAt)),
        adminNote: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.adminNote)),
        sellerId: value.sellerId,
        claimedTrafficVolume: value.claimedTrafficVolume,
        claimedMonthlyRevenue: value.claimedMonthlyRevenue
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    websiteType: string;
    status: string;
    sellerNotes: [] | [string];
    contactName: string;
    submittedAt: _Timestamp;
    submittedBy: Principal;
    description: string;
    contactEmail: string;
    requirements: string;
    budget: string;
    timeline: string;
}): {
    id: bigint;
    websiteType: string;
    status: string;
    sellerNotes?: string;
    contactName: string;
    submittedAt: Timestamp;
    submittedBy: Principal;
    description: string;
    contactEmail: string;
    requirements: string;
    budget: string;
    timeline: string;
} {
    return {
        id: value.id,
        websiteType: value.websiteType,
        status: value.status,
        sellerNotes: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.sellerNotes)),
        contactName: value.contactName,
        submittedAt: value.submittedAt,
        submittedBy: value.submittedBy,
        description: value.description,
        contactEmail: value.contactEmail,
        requirements: value.requirements,
        budget: value.budget,
        timeline: value.timeline
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    notifType: _NotificationType;
    createdAt: _Timestamp;
    read: boolean;
}): {
    id: bigint;
    notifType: NotificationType;
    createdAt: Timestamp;
    read: boolean;
} {
    return {
        id: value.id,
        notifType: from_candid_NotificationType_n36(_uploadFile, _downloadFile, value.notifType),
        createdAt: value.createdAt,
        read: value.read
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completionRate: bigint;
    hasRedFlags: boolean;
    tier: {
        new: null;
    } | {
        trusted: null;
    } | {
        established: null;
    } | {
        caution: null;
    };
    score: bigint;
    isVerified: boolean;
    accountAgeDays: bigint;
    responseTimeHours: bigint;
    avgRating: bigint;
    transactionCount: bigint;
}): {
    completionRate: bigint;
    hasRedFlags: boolean;
    tier: Variant_new_trusted_established_caution;
    score: bigint;
    isVerified: boolean;
    accountAgeDays: bigint;
    responseTimeHours: bigint;
    avgRating: bigint;
    transactionCount: bigint;
} {
    return {
        completionRate: value.completionRate,
        hasRedFlags: value.hasRedFlags,
        tier: from_candid_variant_n44(_uploadFile, _downloadFile, value.tier),
        score: value.score,
        isVerified: value.isVerified,
        accountAgeDays: value.accountAgeDays,
        responseTimeHours: value.responseTimeHours,
        avgRating: value.avgRating,
        transactionCount: value.transactionCount
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trend: _RevenueTrend;
    listingId: bigint;
    trafficVolume: bigint;
    monthlyRevenue: number;
    sourceBreakdowns: Array<_SourceBreakdown>;
}): {
    trend: RevenueTrend;
    listingId: bigint;
    trafficVolume: bigint;
    monthlyRevenue: number;
    sourceBreakdowns: Array<SourceBreakdown>;
} {
    return {
        trend: from_candid_RevenueTrend_n9(_uploadFile, _downloadFile, value.trend),
        listingId: value.listingId,
        trafficVolume: value.trafficVolume,
        monthlyRevenue: value.monthlyRevenue,
        sourceBreakdowns: from_candid_vec_n11(_uploadFile, _downloadFile, value.sourceBreakdowns)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fetchedAt: bigint;
    trafficVolume: bigint;
    revenueTrend: _RevenueTrend;
    monthlyRevenue: number;
    sourceBreakdowns: Array<_SourceBreakdown>;
}): {
    fetchedAt: bigint;
    trafficVolume: bigint;
    revenueTrend: RevenueTrend;
    monthlyRevenue: number;
    sourceBreakdowns: Array<SourceBreakdown>;
} {
    return {
        fetchedAt: value.fetchedAt,
        trafficVolume: value.trafficVolume,
        revenueTrend: from_candid_RevenueTrend_n9(_uploadFile, _downloadFile, value.revenueTrend),
        monthlyRevenue: value.monthlyRevenue,
        sourceBreakdowns: from_candid_vec_n11(_uploadFile, _downloadFile, value.sourceBreakdowns)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    up: null;
} | {
    down: null;
} | {
    flat: null;
}): RevenueTrend {
    return "up" in value ? RevenueTrend.up : "down" in value ? RevenueTrend.down : "flat" in value ? RevenueTrend.flat : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stripe: null;
} | {
    googleAnalytics: null;
} | {
    paypal: null;
} | {
    googleAdSense: null;
}): CredentialSource {
    return "stripe" in value ? CredentialSource.stripe : "googleAnalytics" in value ? CredentialSource.googleAnalytics : "paypal" in value ? CredentialSource.paypal : "googleAdSense" in value ? CredentialSource.googleAdSense : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending: null;
} | {
    sold: null;
}): ListingStatus {
    return "active" in value ? ListingStatus.active : "pending" in value ? ListingStatus.pending : "sold" in value ? ListingStatus.sold : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    outbid: {
        newHighestBid: bigint;
        listingId: bigint;
    };
} | {
    purchaseConfirmed: {
        listingId: bigint;
        amount: bigint;
    };
} | {
    auctionWon: {
        finalPrice: bigint;
        listingId: bigint;
    };
} | {
    priceDrop: {
        listingId: bigint;
        oldPrice: bigint;
        newPrice: bigint;
    };
} | {
    transferUpdate: {
        listingId: bigint;
        message: string;
    };
}): {
    __kind__: "outbid";
    outbid: {
        newHighestBid: bigint;
        listingId: bigint;
    };
} | {
    __kind__: "purchaseConfirmed";
    purchaseConfirmed: {
        listingId: bigint;
        amount: bigint;
    };
} | {
    __kind__: "auctionWon";
    auctionWon: {
        finalPrice: bigint;
        listingId: bigint;
    };
} | {
    __kind__: "priceDrop";
    priceDrop: {
        listingId: bigint;
        oldPrice: bigint;
        newPrice: bigint;
    };
} | {
    __kind__: "transferUpdate";
    transferUpdate: {
        listingId: bigint;
        message: string;
    };
} {
    return "outbid" in value ? {
        __kind__: "outbid",
        outbid: value.outbid
    } : "purchaseConfirmed" in value ? {
        __kind__: "purchaseConfirmed",
        purchaseConfirmed: value.purchaseConfirmed
    } : "auctionWon" in value ? {
        __kind__: "auctionWon",
        auctionWon: value.auctionWon
    } : "priceDrop" in value ? {
        __kind__: "priceDrop",
        priceDrop: value.priceDrop
    } : "transferUpdate" in value ? {
        __kind__: "transferUpdate",
        transferUpdate: value.transferUpdate
    } : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    trusted: null;
} | {
    established: null;
} | {
    caution: null;
}): Variant_new_trusted_established_caution {
    return "new" in value ? Variant_new_trusted_established_caution.new : "trusted" in value ? Variant_new_trusted_established_caution.trusted : "established" in value ? Variant_new_trusted_established_caution.established : "caution" in value ? Variant_new_trusted_established_caution.caution : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    pending: null;
} | {
    unverified: null;
} | {
    rejected: string;
}): {
    __kind__: "verified";
    verified: null;
} | {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "unverified";
    unverified: null;
} | {
    __kind__: "rejected";
    rejected: string;
} {
    return "verified" in value ? {
        __kind__: "verified",
        verified: value.verified
    } : "pending" in value ? {
        __kind__: "pending",
        pending: value.pending
    } : "unverified" in value ? {
        __kind__: "unverified",
        unverified: value.unverified
    } : "rejected" in value ? {
        __kind__: "rejected",
        rejected: value.rejected
    } : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VerificationRequest>): Array<VerificationRequest> {
    return value.map((x)=>from_candid_VerificationRequest_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SourceBreakdown>): Array<SourceBreakdown> {
    return value.map((x)=>from_candid_SourceBreakdown_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Array<Listing> {
    return value.map((x)=>from_candid_Listing_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomOrder>): Array<CustomOrder> {
    return value.map((x)=>from_candid_CustomOrder_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BuyerNotificationView>): Array<BuyerNotificationView> {
    return value.map((x)=>from_candid_BuyerNotificationView_n34(_uploadFile, _downloadFile, x));
}
function to_candid_CredentialSource_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CredentialSource): _CredentialSource {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid_CredentialToken_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CredentialToken): _CredentialToken {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_ListingFilter_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingFilter): _ListingFilter {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_SearchQuery_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SearchQuery): _SearchQuery {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_ValuationInput_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ValuationInput): _ValuationInput {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    domainAuthority: bigint;
    revenueType: Variant_ads_recurring_affiliate_product;
    monthlyTraffic: bigint;
    trafficDiversification: Variant_mixed_diverse_single;
    revenueTrend: RevenueTrend;
    domainAgeYears: bigint;
    monthlyRevenue: bigint;
}): {
    domainAuthority: bigint;
    revenueType: {
        ads: null;
    } | {
        recurring: null;
    } | {
        affiliate: null;
    } | {
        product: null;
    };
    monthlyTraffic: bigint;
    trafficDiversification: {
        mixed: null;
    } | {
        diverse: null;
    } | {
        single: null;
    };
    revenueTrend: {
        up: null;
    } | {
        down: null;
    } | {
        flat: null;
    };
    domainAgeYears: bigint;
    monthlyRevenue: bigint;
} {
    return {
        domainAuthority: value.domainAuthority,
        revenueType: to_candid_variant_n20(_uploadFile, _downloadFile, value.revenueType),
        monthlyTraffic: value.monthlyTraffic,
        trafficDiversification: to_candid_variant_n21(_uploadFile, _downloadFile, value.trafficDiversification),
        revenueTrend: to_candid_variant_n22(_uploadFile, _downloadFile, value.revenueTrend),
        domainAgeYears: value.domainAgeYears,
        monthlyRevenue: value.monthlyRevenue
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    platform?: string;
    maxPrice?: bigint;
    niche?: string;
}): {
    platform: [] | [string];
    maxPrice: [] | [bigint];
    niche: [] | [string];
} {
    return {
        platform: value.platform ? candid_some(value.platform) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        niche: value.niche ? candid_some(value.niche) : candid_none()
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    naturalLanguage?: string;
    cmsType?: string;
    sortBy: Variant_newest_priceDesc_priceAsc_bestMatch_highestRating;
    minTraffic?: bigint;
    countryTraffic?: string;
    maxRevenue?: bigint;
    minAgeYears?: bigint;
    niche?: string;
    monetizationType?: string;
    minSeoScore?: bigint;
    minRevenue?: bigint;
    maxTraffic?: bigint;
}): {
    naturalLanguage: [] | [string];
    cmsType: [] | [string];
    sortBy: {
        newest: null;
    } | {
        priceDesc: null;
    } | {
        priceAsc: null;
    } | {
        bestMatch: null;
    } | {
        highestRating: null;
    };
    minTraffic: [] | [bigint];
    countryTraffic: [] | [string];
    maxRevenue: [] | [bigint];
    minAgeYears: [] | [bigint];
    niche: [] | [string];
    monetizationType: [] | [string];
    minSeoScore: [] | [bigint];
    minRevenue: [] | [bigint];
    maxTraffic: [] | [bigint];
} {
    return {
        naturalLanguage: value.naturalLanguage ? candid_some(value.naturalLanguage) : candid_none(),
        cmsType: value.cmsType ? candid_some(value.cmsType) : candid_none(),
        sortBy: to_candid_variant_n41(_uploadFile, _downloadFile, value.sortBy),
        minTraffic: value.minTraffic ? candid_some(value.minTraffic) : candid_none(),
        countryTraffic: value.countryTraffic ? candid_some(value.countryTraffic) : candid_none(),
        maxRevenue: value.maxRevenue ? candid_some(value.maxRevenue) : candid_none(),
        minAgeYears: value.minAgeYears ? candid_some(value.minAgeYears) : candid_none(),
        niche: value.niche ? candid_some(value.niche) : candid_none(),
        monetizationType: value.monetizationType ? candid_some(value.monetizationType) : candid_none(),
        minSeoScore: value.minSeoScore ? candid_some(value.minSeoScore) : candid_none(),
        minRevenue: value.minRevenue ? candid_some(value.minRevenue) : candid_none(),
        maxTraffic: value.maxTraffic ? candid_some(value.maxTraffic) : candid_none()
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: string;
    refreshToken?: string;
    source: CredentialSource;
}): {
    token: string;
    refreshToken: [] | [string];
    source: _CredentialSource;
} {
    return {
        token: value.token,
        refreshToken: value.refreshToken ? candid_some(value.refreshToken) : candid_none(),
        source: to_candid_CredentialSource_n52(_uploadFile, _downloadFile, value.source)
    };
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_ads_recurring_affiliate_product): {
    ads: null;
} | {
    recurring: null;
} | {
    affiliate: null;
} | {
    product: null;
} {
    return value == Variant_ads_recurring_affiliate_product.ads ? {
        ads: null
    } : value == Variant_ads_recurring_affiliate_product.recurring ? {
        recurring: null
    } : value == Variant_ads_recurring_affiliate_product.affiliate ? {
        affiliate: null
    } : value == Variant_ads_recurring_affiliate_product.product ? {
        product: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_mixed_diverse_single): {
    mixed: null;
} | {
    diverse: null;
} | {
    single: null;
} {
    return value == Variant_mixed_diverse_single.mixed ? {
        mixed: null
    } : value == Variant_mixed_diverse_single.diverse ? {
        diverse: null
    } : value == Variant_mixed_diverse_single.single ? {
        single: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RevenueTrend): {
    up: null;
} | {
    down: null;
} | {
    flat: null;
} {
    return value == RevenueTrend.up ? {
        up: null
    } : value == RevenueTrend.down ? {
        down: null
    } : value == RevenueTrend.flat ? {
        flat: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_newest_priceDesc_priceAsc_bestMatch_highestRating): {
    newest: null;
} | {
    priceDesc: null;
} | {
    priceAsc: null;
} | {
    bestMatch: null;
} | {
    highestRating: null;
} {
    return value == Variant_newest_priceDesc_priceAsc_bestMatch_highestRating.newest ? {
        newest: null
    } : value == Variant_newest_priceDesc_priceAsc_bestMatch_highestRating.priceDesc ? {
        priceDesc: null
    } : value == Variant_newest_priceDesc_priceAsc_bestMatch_highestRating.priceAsc ? {
        priceAsc: null
    } : value == Variant_newest_priceDesc_priceAsc_bestMatch_highestRating.bestMatch ? {
        bestMatch: null
    } : value == Variant_newest_priceDesc_priceAsc_bestMatch_highestRating.highestRating ? {
        highestRating: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CredentialSource): {
    stripe: null;
} | {
    googleAnalytics: null;
} | {
    paypal: null;
} | {
    googleAdSense: null;
} {
    return value == CredentialSource.stripe ? {
        stripe: null
    } : value == CredentialSource.googleAnalytics ? {
        googleAnalytics: null
    } : value == CredentialSource.paypal ? {
        paypal: null
    } : value == CredentialSource.googleAdSense ? {
        googleAdSense: null
    } : value;
}
function to_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CredentialToken>): Array<_CredentialToken> {
    return value.map((x)=>to_candid_CredentialToken_n50(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
